// <auto-generated />

namespace WindowsPhoneJsonWireServer
{
    using System;

    using Newtonsoft.Json;

    public class FindElementObject
    {
        #region Public Properties

        [JsonProperty("sessionId")]
        public string SessionId { get; set; }

        [JsonProperty("using")]
        public string UsingMethod { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }

        #endregion
    }

    public class JsonKeysContent
    {
        #region Public Properties

        [JsonProperty("sessionId")]
        public string SessionId { get; set; }

        [JsonProperty("value")]
        public string[] Value { get; set; }

        #endregion
    }

    public class WebElement
    {
        #region Constructors and Destructors

        public WebElement(string element)
        {
            this.Element = element;
        }

        #endregion

        #region Public Properties

        [JsonProperty("ELEMENT")]
        public string Element { get; set; }

        #endregion
    }

    public class JsonResponse
    {
        #region Fields

        [JsonProperty("sessionId")]
        public string SessionId = "awesomeSessionId";

        #endregion

        #region Constructors and Destructors

        public JsonResponse(ResponseStatus status, object value)
        {
            this.Status = status;
            this.Value = value;
        }

        #endregion

        #region Public Properties

        [JsonProperty("status")]
        public ResponseStatus Status { get; set; }

        [JsonProperty("value")]
        public object Value { get; set; }

        #endregion
    }
}
