// <auto-generated />
namespace WindowsPhoneDriver.Common
{
    using System;
    using System.Collections.Generic;

    using Newtonsoft.Json;

    public class JsonWebElementContent
    {
        #region Constructors and Destructors

        public JsonWebElementContent(string element)
        {
            this.Element = element;
        }

        #endregion

        #region Public Properties

        [JsonProperty("ELEMENT")]
        public string Element { get; set; }

        #endregion
    }

    internal class JsonResponse
    {
        #region Constructors and Destructors

        public JsonResponse(string sessionId, ResponseStatus responseCode, object value)
        {
            this.SessionId = sessionId;
            this.Status = responseCode;

            this.Value = (responseCode == ResponseStatus.Success) ? value : this.PrepareErrorResponse(value);
        }

        private object PrepareErrorResponse(object value)
        {
            var result = new Dictionary<string, string> { { "error", JsonErrorCodes.Parse(this.Status) } };

            string message;
            var exception = value as Exception;
            if (exception != null)
            {
                message = exception.Message;
                result.Add("stacktrace", exception.StackTrace);
            }
            else
            {
                message = value.ToString();
            }

            result.Add("message", message);
            return result;
        }

        #endregion

        #region Public Properties

        [JsonProperty("sessionId")]
        public string SessionId { get; set; }

        [JsonProperty("status")]
        public ResponseStatus Status { get; set; }

        [JsonProperty("value")]
        public object Value { get; set; }

        #endregion
    }

    public class JsonCommand
    {
        #region Public Properties

        /// <summary>
        /// Gets the command name
        /// 
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets the parameters of the command
        /// 
        /// </summary>
        [JsonProperty("parameters")]
        public Dictionary<string, object> Parameters { get; set; }

        /// <summary>
        /// Gets the SessionID of the command
        /// 
        /// </summary>
        [JsonProperty("sessionId")]
        public string SessionId { get; set; }

        #endregion
    }
}
